require:
  - rubocop/cop/internal_affairs

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/*_helper.rb'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.7.4
  SuggestExtensions: false

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/AccessorGrouping:
  Exclude:
    - 'lib/rubocop/formatter/base_formatter.rb'
    - 'lib/rubocop/cop/offense.rb'

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
    - 'spec/rubocop/cop/style/ip_addresses_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/models/application_record.rb'

Layout/EndOfLine:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/RedundantLineBreak:
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|specify|shared_examples|include_examples|it_behaves_like) ["']/
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Max: 40
  IgnoredMethods: ['describe', 'context', 'specify', 'it']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'lib/rubocop/config_obsoletion.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*.rb'
    - 'app/models/ability.rb'

Metrics/AbcSize:
  Exclude:
    # Skipped as these are required functionality and cannot be reduced
    - 'app/controllers/concerns/accessible.rb'
    - 'app/models/ability.rb'

Naming/InclusiveLanguage:
  FlaggedTerms:
    offence:
      Suggestions:
        - offense
  Exclude:
    - 'lib/rubocop/cop/naming/inclusive_language.rb'

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/errors_controller.rb'

InternalAffairs/ExampleDescription:
  Include:
    - 'spec/rubocop/cop/**/*.rb'

InternalAffairs/UndefinedConfig:
  Include:
    - 'lib/rubocop/cop/**/*.rb'
  Exclude:
    - 'lib/rubocop/cop/correctors/**/*.rb'
    - 'lib/rubocop/cop/mixin/**/*.rb'

InternalAffairs/StyleDetectedApiUse:
  Exclude:
    - 'lib/rubocop/cop/mixin/percent_array.rb'
