require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/product_reports', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ProductReport. As you add validations to ProductReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { content: 'Content', product: FactoryBot.create(:product), customer:  FactoryBot.create(:customer) }
  end

  let(:invalid_attributes) do
    { content: '', product: FactoryBot.create(:product), customer:  FactoryBot.create(:customer)  }
  end

  before { login_as(FactoryBot.create(:admin), scope: :staff) }

  describe 'GET /index' do
    it 'renders a successful response' do
      ProductReport.create! valid_attributes
      get product_reports_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      product_report = ProductReport.create! valid_attributes
      get product_report_url(product_report)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_product_report_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ProductReport' do
        expect do
          post product_reports_url, params: { product_report: valid_attributes }
        end.to change(ProductReport, :count).by(1)
      end

      it 'redirects to the created product_report' do
        post product_reports_url, params: { product_report: valid_attributes }
        expect(response).to redirect_to(product_report_url(ProductReport.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ProductReport' do
        expect do
          post product_reports_url, params: { product_report: invalid_attributes }
        end.to change(ProductReport, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post product_reports_url, params: { product_report: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested product_report' do
      product_report = ProductReport.create! valid_attributes
      expect do
        delete product_report_url(product_report)
      end.to change(ProductReport, :count).by(-1)
    end

    it 'redirects to the product_reports list' do
      product_report = ProductReport.create! valid_attributes
      delete product_report_url(product_report)
      expect(response).to redirect_to(product_reports_url)
    end
  end
end
